import React from 'react';
import type { Metadata } from 'next';

import './globals.css';

import { RootLayout } from '@/app/layouts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={'antialiased'}>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
